### ISSUE TITLE
error with --edit-format cedarscript

### ISSUE THREAD

**Issue by loudmu** [CEDARScript/cedarscript-integration-aider#3]
aider --model gemini/gemini-1.5-flash-latest --edit-format cedarscript
Traceback (most recent call last):
  File "/home/loudmu/aider-env/bin/aider", line 5, in <module>
    from aider.main import main
  File "/home/loudmu/aider-env/lib/python3.11/site-packages/aider/main.py", line 18, in <module>
    from aider.coders import Coder
  File "/home/loudmu/aider-env/lib/python3.11/site-packages/aider/coders/__init__.py", line 4, in <module>
    from .cedarscript_coder import CEDARScriptCoderRaw, CEDARScriptCoderW, CEDARScriptCoderGrammar
  File "/home/loudmu/aider-env/lib/python3.11/site-packages/aider/coders/cedarscript_coder.py", line 5, in <module>
    from aider.coders.folder_coder import FolderCoder
  File "/home/loudmu/aider-env/lib/python3.11/site-packages/aider/coders/folder_coder.py", line 4, in <module>
    from pylibtypes import create_named_subclass, load_class_attrs_from_folder, FolderBasedAttrsError
  File "/home/loudmu/aider-env/lib/python3.11/site-packages/pylibtypes/__init__.py", line 7, in <module>
    from .named_subclass_factory import create_named_subclass
  File "/home/loudmu/aider-env/lib/python3.11/site-packages/pylibtypes/named_subclass_factory.py", line 4
    def create_named_subclass[T](base_class: Type[T], subclass_suffix: str, prefix: str = "") -> Type[T]:
                             ^
SyntaxError: expected '('

**Comment by elifarley** [comment]
Should be fixed by now.

Please check the [updated installation details](https://github.com/CEDARScript/cedarscript-integration-aider/blob/main/README.md#how-to-use-it).

**Comment by loudmu** [comment]
thank you it worked .  i recommend using  a virtual environment  (venv or conda)
